import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'dist/**',
      'coverage/**',
      '*.config.js',
      '*.config.mjs',
      '*.config.ts',
      'playwright-report/**',
      'test-results/**',
      '.storybook/**',
      'storybook-static/**',
      'sentry.*.config.ts',
      'instrumentation.ts',
      'scripts/**', // Scripts often have looser rules
      'next-env.d.ts', // Auto-generated by Next.js
      'tests/load/**', // k6 load tests have different globals
    ],
  },
  // Base recommended rules
  js.configs.recommended,
  // TypeScript recommended (type-checked off for performance)
  ...tseslint.configs.recommended,
  // All source files
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.mjs'],
    plugins: {
      'react-hooks': reactHooks,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2021,
        React: 'readonly',
        JSX: 'readonly',
      },
    },
    rules: {
      // React hooks rules
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // Allow unused vars when prefixed with underscore
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Relax some rules for development
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      'no-unused-vars': 'off', // Use TS version
      'no-useless-escape': 'warn', // Common in regex patterns
      // Convert common errors to warnings for gradual improvement
      'prefer-const': 'warn',
      'no-case-declarations': 'warn',
      'no-empty': 'warn',
      '@typescript-eslint/no-this-alias': 'warn',
      'no-loss-of-precision': 'warn',
      'no-misleading-character-class': 'warn',
      'no-unsafe-finally': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      'no-control-regex': 'warn',
    },
  },
  // Test and story files - relax some rules
  {
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/*.stories.ts',
      '**/*.stories.tsx',
      'tests/**/*',
      '**/testing/**/*',
    ],
    rules: {
      'react-hooks/rules-of-hooks': 'off', // Tests/stories may have different patterns
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
