/**
 * AI Disclaimer Component
 *
 * Phase 1, Week 2, Day 5
 *
 * Provides clear disclosure about AI-generated content
 * and analysis methodology for transparency and compliance.
 */

'use client';

import React, { useState } from 'react';

// ================================================================
// TYPES
// ================================================================

export type DisclaimerVariant = 'banner' | 'inline' | 'modal' | 'tooltip' | 'footer';
export type DisclaimerSize = 'sm' | 'md' | 'lg';

export interface AIDisclaimerProps {
  /** Display variant */
  variant?: DisclaimerVariant;
  /** Size */
  size?: DisclaimerSize;
  /** Show expanded details */
  expandable?: boolean;
  /** Default expanded state */
  defaultExpanded?: boolean;
  /** Custom class name */
  className?: string;
  /** Callback when dismissed */
  onDismiss?: () => void;
  /** Show dismiss button */
  dismissible?: boolean;
  /** Context-specific message */
  context?: 'analysis' | 'recommendations' | 'score' | 'general';
}

// ================================================================
// CONTENT
// ================================================================

const DISCLAIMER_CONTENT = {
  analysis: {
    title: 'AI-Powered Analysis',
    short: 'This analysis is generated using artificial intelligence and may not be 100% accurate.',
    full: `Our AI Perception Score is calculated by querying multiple AI assistants (ChatGPT, Claude, Gemini, Perplexity)
    and analyzing their responses about your brand. Results represent how these AI systems currently perceive your brand
    based on their training data and knowledge. AI responses can vary and may contain inaccuracies. This analysis should
    be used as one input among many in your marketing strategy, not as the sole basis for business decisions.`,
  },
  recommendations: {
    title: 'AI-Generated Recommendations',
    short: 'Recommendations are generated by AI and should be reviewed by a human expert.',
    full: `The recommendations provided are automatically generated based on AI analysis of your brand\'s current
    AI perception. While these suggestions are based on best practices and pattern recognition, they may not account
    for all aspects of your specific business context. We recommend having a marketing professional review these
    recommendations before implementation. Results are not guaranteed.`,
  },
  score: {
    title: 'About Your AI Perception Score',
    short: 'Scores reflect current AI perception and may change as AI models are updated.',
    full: `Your AI Perception Score is a snapshot of how major AI assistants currently perceive and recommend your brand.
    This score is calculated using proprietary algorithms that analyze AI responses across multiple dimensions.
    Important considerations:
    • AI model knowledge has cutoff dates and may not reflect recent changes
    • AI responses can vary between queries
    • Scores are relative and should be compared to industry benchmarks
    • Regular monitoring is recommended as AI models are frequently updated`,
  },
  general: {
    title: 'AI Disclosure',
    short: 'This product uses artificial intelligence to provide insights and recommendations.',
    full: `AI Perception uses artificial intelligence technology to analyze how AI systems perceive brands.
    Our service queries multiple AI providers, processes their responses, and generates insights and
    recommendations. While we strive for accuracy, AI-generated content may contain errors or
    inaccuracies. Users should exercise judgment when acting on AI-generated information.`,
  },
};

const METHODOLOGY_POINTS = [
  'We query ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), and Perplexity',
  'Responses are analyzed for brand mentions, sentiment, accuracy, and positioning',
  'Scores are calculated using a weighted algorithm across multiple dimensions',
  'Results are compared against industry benchmarks for context',
  'Analysis is performed at a specific point in time and may change',
];

// ================================================================
// COMPONENT
// ================================================================

export function AIDisclaimer({
  variant = 'inline',
  size = 'md',
  expandable = true,
  defaultExpanded = false,
  className = '',
  onDismiss,
  dismissible = false,
  context = 'general',
}: AIDisclaimerProps): React.ReactElement | null {
  const [isExpanded, setIsExpanded] = useState(defaultExpanded);
  const [isDismissed, setIsDismissed] = useState(false);

  const content = DISCLAIMER_CONTENT[context];

  if (isDismissed) return null;

  const handleDismiss = () => {
    setIsDismissed(true);
    onDismiss?.();
  };

  // Size classes
  const sizeClasses = {
    sm: 'text-xs',
    md: 'text-sm',
    lg: 'text-base',
  };

  // Variant-specific rendering
  switch (variant) {
    case 'banner':
      return (
        <div
          className={`bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 ${className}`}
          role="alert"
          aria-label="AI Disclaimer"
        >
          <div className="flex items-start gap-3">
            <AIIcon className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h4 className={`font-medium text-blue-400 ${sizeClasses[size]}`}>
                  {content.title}
                </h4>
                {dismissible && (
                  <button
                    onClick={handleDismiss}
                    className="text-blue-400 hover:text-blue-300 p-1"
                    aria-label="Dismiss disclaimer"
                  >
                    <CloseIcon className="w-4 h-4" />
                  </button>
                )}
              </div>
              <p className={`text-blue-300/80 mt-1 ${sizeClasses[size]}`}>
                {isExpanded ? content.full : content.short}
              </p>
              {expandable && (
                <button
                  onClick={() => setIsExpanded(!isExpanded)}
                  className={`text-blue-400 hover:text-blue-300 mt-2 underline ${sizeClasses[size]}`}
                >
                  {isExpanded ? 'Show less' : 'Learn more'}
                </button>
              )}
            </div>
          </div>
        </div>
      );

    case 'inline':
      return (
        <div
          className={`flex items-start gap-2 text-[var(--text-tertiary)] ${sizeClasses[size]} ${className}`}
          role="note"
          aria-label="AI Disclaimer"
        >
          <InfoIcon className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <div>
            <span>{content.short}</span>
            {expandable && (
              <button
                onClick={() => setIsExpanded(!isExpanded)}
                className="text-[var(--accent-primary)] hover:underline ml-1"
              >
                {isExpanded ? 'Less' : 'More'}
              </button>
            )}
            {isExpanded && (
              <p className="mt-2 text-[var(--text-secondary)]">{content.full}</p>
            )}
          </div>
        </div>
      );

    case 'footer':
      return (
        <footer
          className={`border-t border-[var(--border-primary)] pt-4 mt-6 ${className}`}
          role="contentinfo"
          aria-label="AI Methodology Disclaimer"
        >
          <div className="flex items-center gap-2 mb-3">
            <AIIcon className="w-4 h-4 text-[var(--text-tertiary)]" />
            <h4 className={`font-medium text-[var(--text-secondary)] ${sizeClasses[size]}`}>
              {content.title}
            </h4>
          </div>
          <p className={`text-[var(--text-tertiary)] ${sizeClasses[size]}`}>
            {content.short}
          </p>
          {expandable && isExpanded && (
            <div className="mt-4 space-y-3">
              <p className={`text-[var(--text-tertiary)] ${sizeClasses[size]}`}>
                {content.full}
              </p>
              <div className="mt-4">
                <h5 className={`font-medium text-[var(--text-secondary)] mb-2 ${sizeClasses[size]}`}>
                  Our Methodology:
                </h5>
                <ul className={`list-disc list-inside space-y-1 text-[var(--text-tertiary)] ${sizeClasses[size]}`}>
                  {METHODOLOGY_POINTS.map((point, i) => (
                    <li key={i}>{point}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
          {expandable && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className={`text-[var(--accent-primary)] hover:underline mt-2 ${sizeClasses[size]}`}
            >
              {isExpanded ? 'Show less' : 'View full methodology'}
            </button>
          )}
        </footer>
      );

    case 'tooltip':
      return (
        <div
          className={`bg-[var(--bg-secondary)] border border-[var(--border-primary)] rounded-lg p-3 shadow-lg max-w-xs ${className}`}
          role="tooltip"
          aria-label="AI Disclaimer"
        >
          <div className="flex items-center gap-2 mb-2">
            <AIIcon className="w-4 h-4 text-[var(--accent-primary)]" />
            <span className={`font-medium text-[var(--text-primary)] ${sizeClasses[size]}`}>
              {content.title}
            </span>
          </div>
          <p className={`text-[var(--text-secondary)] ${sizeClasses[size]}`}>
            {content.short}
          </p>
        </div>
      );

    case 'modal':
      return (
        <div
          className={`bg-[var(--bg-card)] border border-[var(--border-primary)] rounded-xl p-6 max-w-lg ${className}`}
          role="dialog"
          aria-label="AI Disclaimer"
          aria-modal="true"
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center">
                <AIIcon className="w-6 h-6 text-blue-500" />
              </div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)]">
                {content.title}
              </h3>
            </div>
            {dismissible && (
              <button
                onClick={handleDismiss}
                className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] p-2"
                aria-label="Close"
              >
                <CloseIcon className="w-5 h-5" />
              </button>
            )}
          </div>

          <p className={`text-[var(--text-secondary)] mb-4 ${sizeClasses[size]}`}>
            {content.full}
          </p>

          <div className="bg-[var(--bg-tertiary)] rounded-lg p-4">
            <h4 className={`font-medium text-[var(--text-primary)] mb-2 ${sizeClasses[size]}`}>
              Our Analysis Methodology:
            </h4>
            <ul className={`space-y-2 text-[var(--text-secondary)] ${sizeClasses[size]}`}>
              {METHODOLOGY_POINTS.map((point, i) => (
                <li key={i} className="flex items-start gap-2">
                  <CheckIcon className="w-4 h-4 text-[var(--success)] flex-shrink-0 mt-0.5" />
                  {point}
                </li>
              ))}
            </ul>
          </div>

          {dismissible && (
            <button
              onClick={handleDismiss}
              className="w-full mt-4 py-2 bg-[var(--accent-primary)] text-white rounded-lg hover:bg-[var(--accent-primary-hover)] transition-colors"
            >
              I Understand
            </button>
          )}
        </div>
      );

    default:
      return null;
  }
}

// ================================================================
// ICONS
// ================================================================

function AIIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
    </svg>
  );
}

function InfoIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <circle cx="12" cy="12" r="10" />
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 16v-4M12 8h.01" />
    </svg>
  );
}

function CloseIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  );
}

function CheckIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
    </svg>
  );
}

// ================================================================
// EXPORTS
// ================================================================

export default AIDisclaimer;
